repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff formatter
        entry: ruff format --check
        language: python
        additional_dependencies: ["ruff>=0.11"]
        types: [python]
      - id: ruff-check
        name: Ruff linter
        entry: ruff check
        language: python
        additional_dependencies: ["ruff>=0.11"]
        types: [python]
